=== ben2117/PollingSystem/FinalPolSysApp/WEB-INF/polling.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/polling" xmlns:tns="http://www.example.org/polling"
	elementFormDefault="qualified">

	<!-- Type declarations -->
	<!-- Not being used. Using default validations -->
	<xs:simpleType name="dt"> 
		<xs:restriction base="xs:dateTime"> 
		<xs:pattern value="\d{1,4}-\d{1,2}-\d{1,2}T\d{1,2}:\d{1,2}:\d{1,2}"/> 
		</xs:restriction> 
	</xs:simpleType>


	<!-- Element declarations -->
	<xs:element name="users">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="user" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="userID" type="xs:positiveInteger" />
							<xs:element name="username" type="xs:string" />
							<xs:element name="fullName" type="xs:string" />
							<xs:element name="password" type="xs:string" />
							<xs:element name="poll" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="pollID" type="xs:positiveInteger" />
										<xs:element name="pollCreator" type="xs:string" />
										<xs:element name="pollTitle" type="xs:string" />
										<xs:element name="pollDate" type="xs:dateTime" />
										<xs:element name="pollLocation" type="xs:string" />
										<xs:element name="pollDescription" type="xs:string" />
										<xs:element name="status" type="xs:string" />
										<xs:element name="VoteOption" minOccurs="0"
											maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="voteOptionID" type="xs:positiveInteger" />
													<xs:element name="voteOption" type="xs:dateTime" />
													<xs:element name="vote" minOccurs="0" maxOccurs="unbounded">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="votername" minOccurs="0"
																	maxOccurs="unbounded" />
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ben2117/PollingSystem/FinalPolSysApp/WEB-INF/Polling.xml
<?xml version="1.0" encoding="UTF-8"?>


<users ><!-- xmlns="http://www.example.org/polling"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.example.org/polling polling.xsd" -->

	<user>
		<userID>1</userID>
		<username>rod</username>
		<fullName>rosa rod</fullName>
		<password>123</password>
				<poll>
					<pollID>1</pollID>
					<pollCreator>rosa rod</pollCreator>
					<pollTitle>pollTitle1</pollTitle>
					<pollDate>01/05/16 21:38:01</pollDate>
					<pollLocation>Lee St, Kiama Rm</pollLocation>
					<pollDescription>Project Disc</pollDescription>
					<status>open</status>
					
					<VoteOption>
						<voteOptionID>1</voteOptionID>
						<voteOption>8/05/16 9am</voteOption>
						<vote>
							<votername>Marral</votername>
						</vote>
						<vote>	
							<votername>Narrel</votername>
						</vote>
						<vote>
							<votername>Carrel</votername>
						</vote>
					</VoteOption>
					<VoteOption>
						<voteOptionID>2</voteOptionID>
						<voteOption>15/05/16 9am</voteOption>
						<vote>
							<votername>Crystal</votername>
						</vote>
					</VoteOption>
					<VoteOption>
						<voteOptionID>3</voteOptionID>
						<voteOption>12/05/16 10am</voteOption>
					</VoteOption>
					
				</poll>
	</user>
</users>
